fixed_header: 1
scrolltop_display: 1
_core:
  default_config_hash: gyZztpEsAGPxx9Hw1Lj7kU_JBNnBX6S-MxjtMxSSaRU
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo2_0.png'
favicon:
  use_default: true
  path: ''
header: ''
scrolltop: ''
